name: Test Github Action

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test rendering example_scenes.py
        uses: ./
        id: renderer
        with:
          source_file: test/example_scenes.py
          scene_names: "OpeningManimExample WriteStuff"
          args: "--high_quality"
      - name: Save output as artifacts
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Videos
          path: ${{ steps.renderer.outputs.video_path }}
          